version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - '8000:8000' 
        container_name: xbbg-web-server
        volumes:
            - .:/app
        restart: always